TEST_VALUE:
  name: cookie

FEISHU_CONFIG:
  FEISHU_URL: https://open.feishu.cn/open-apis
  FEISHU_API_HOST: https://open.feishu.cn
  FEISHU_APP_ID: cli_a48efb12a93ad00d
  FEISHU_APP_SECRET: GkkJ4g5VXHIAVWV9yrVSpdLPZi3tkTTR

APP_TOKEN_CACHE_KEY: APP_TOKEN_CACHE_KEY


MONGODB_CONFIG:
  name: "fast_gateway"          # 自定义次数据库链接名称
  type: mongodb                      # 数据库链接类型
  url: "mongodb://mongo:mongo@localhost:27017/fast_gateway?authSource=admin"   # 数据库链接地址
  username: "mongo"                   # 数据库链接用户名
  password: "mongo"                 # 数据库链接密码
  database: "fast_gateway"      # 数据库名
  entities: "mongo"                  # 自定义加载类型
  logging: true                     # 数据库打印日志
  synchronize: true                  # 是否开启同步数据表功能
